### ISSUE TITLE
Exception generated on New Message operation with add-on enabled.

### ISSUE THREAD

**Issue by Pazu** [agersant/smart-dictionary-switcher#2]
Error: [Exception... "'JavaScript component does not have a method named: "NotifyComposeFieldsReady"' when calling method: [nsIMsgComposeStateListener::NotifyComposeFieldsReady]"  nsresult: "0x80570030 (NS_ERROR_XPC_JSOBJECT_HAS_NO_FUNCTION_NAMED)"  location: "JS frame :: chrome://messenger/content/messengercompose/MsgComposeCommands.js :: InitEditor :: line 4620"  data: no]
Source File: chrome://messenger/content/messengercompose/MsgComposeCommands.js
Line: 4620

**Comment by agersant** [comment]
Fixed in version 1.1 which is currently pending review from Mozilla and should be published in a few days.
Thanks for your feedback!
