### ISSUE TITLE
Recognizes only French language

### ISSUE THREAD

**Issue by bosla** [agersant/smart-dictionary-switcher#4]
I really love the idea of this addon but it only works sometimes. It seems that it does not recognize most of my dictionaries... it only recognizes French. What can I do? Any way of debugging it?

**Comment by agersant** [comment]
Hi and thanks for your comment.
There is currently a bug in Thunderbird which breaks the detection of installed dictionaries ([bug tracker link](https://bugzilla.mozilla.org/show_bug.cgi?id=843727)) and I guess this is what you are experiencing.

I will open a ticket about adding support for debugging info. Thanks again.

**Comment by agersant** [comment]
[New ticket opened](https://github.com/agersant/smart-dictionary-switcher/issues/5)
